### ISSUE TITLE
The extension download server returned an unexpected status code (503)

### ISSUE THREAD

**Issue by halfnibble** [GwynethLlewelyn/Go.novaextension#10]
Not sure if it's just me or not, but I consistently get this popup when trying to install this Go extension in Nova (other extensions install without issue).

"The extension download server returned an unexpected status code (503)"

<img width="280" alt="Screen Shot 2021-02-02 at 5 50 53 PM" src="https://user-images.githubusercontent.com/5139752/106686567-61250480-657f-11eb-8ff1-32f3091ecd05.png">

**Comment by GwynethLlewelyn** [comment]
Unfortunately, it's all of us — I'm currently on Twitter with their tech support, eagerly awaiting for some more feedback. Allegedly, it's something related to a security upgrade done on their extension library server; this wasn't the only affected plugin...

Until this gets fixed by, the only solution is to install it manually (e.g. by cloning this repository)

**Comment by GwynethLlewelyn** [comment]
Sorry, I still don't have an update on this. I've been on Twitter with Panic most of yesterday and will do the same today; hopefully, they can figure out _what_ is happening, and why it just affects some plugins and not others.

**Comment by GwynethLlewelyn** [comment]
All right, things should be working now! According to Panic, there was an issue affecting some countries, which might also impact the download time for the latest updates — I had to wait around a minute (46s to be more precise!) until everything was downloaded and activated. This seems to affect at least users in Portugal 🇵🇹 , Spain 🇪🇸 , Germany 🇩🇪  and Switzerland 🇨🇭 — but possibly others as well.

I'll close this for now, and thank Thomas Lister from Panic for all his technical support help 👍
